[package]
name = "dqcsim-cli"
version = "0.1.0"
authors = ["Matthijs Brobbel", "Jeroen van Straten"]
edition = "2018"

[dependencies]
dqcsim = { path = "../dqcsim" }

structopt = "0.2"
signal-hook = "0.1"
failure = "0.1"
