[package]
name = "dqcsim-cli"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
dqcsim = { path = "../dqcsim" }

log = "0.4"
structopt = "0.2"
signal-hook = "0.1"
