[tasks.install]
dependencies = ["release"]
command = "make"
args = ["install"]

[tasks.build_examples]
command = "cargo"
args = ["build", "--examples"]

[tasks.kcov-test]
env = { "RUSTFLAGS" = "-C link-dead-code" }
run_task = "test_kcov"

[tasks.test_kcov]
command = "cargo"
dependencies = ["build_examples", "build"]
args = ["test", "--features", "kcov", "--", "--test-threads", "1"]
