[package]
name = "enum-variants-derive"
version = "0.1.0"
authors = ["Jeroen van Straten <jeroen.van.straten@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
proc-quote = "0.2"
