---
kind: pipeline
name: python-3-5

steps:
- name: test
  image: python:3.5
  commands:
  - apt-get update && apt-get install -y swig
  - python setup.py build test bdist_wheel

---
kind: pipeline
name: python-3-6

steps:
- name: test
  image: python:3.6
  commands:
  - apt-get update && apt-get install -y swig
  - python setup.py build test bdist_wheel

---
kind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands:
  - apt-get update && apt-get install -y swig
  - python setup.py build test bdist_wheel
