language: rust
sudo: false
cache: cargo

rust:
  - stable
  - nightly

install:
  - rustup component add clippy
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cargo fmt
  - cargo clippy
  - cargo build
  - cargo test
  - cd book && mdbook build && mdbook test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book/book
  keep-history: false
  on:
    branch: master
