sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
  include:
    - &rust-job
      os: osx
      language: rust
      rust: stable
      cache:
        directories:
          - $HOME/.cargo
      before_cache:
        - rm -rf $HOME/.cargo/registry
      install:
        - rustup component add clippy --toolchain="$TRAVIS_RUST_VERSION" || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
        - cargo clippy --all-targets --all-features -- -Dwarnings
        - cargo build --all-targets --all-features
        - cargo test --all-targets
    - <<: *rust-job
      os: linux
      after_success:
        - mdbook --version || cargo install --debug mdbook --vers "0.2.3"
      before_deploy:
        - cargo doc --all-features
        - cd doc && mdbook build && mdbook test
        - cp -R $TRAVIS_BUILD_DIR/target/doc/ $TRAVIS_BUILD_DIR/doc/book/doc_
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: doc/book
        keep-history: false
        on:
          branch: master
    - <<: *rust-job
      rust: nightly
    - <<: *rust-job
      os: linux
      rust: nightly
    - name: "Coverage"
      language: rust
      rust: stable
      os: linux
      dist: xenial
      env:
        - RUSTFLAGS="-C link-dead-code"
        - PATH=$PATH:$HOME/kcov/bin/
        - DQCSIM_DEBUG=""
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - swig
            # kcov
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      install:
        - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
        - tar xzf master.tar.gz
        - cd kcov-master
        - mkdir build
        - cd build
        - cmake -DCMAKE_INSTALL_PREFIX=$HOME/kcov ..
        - make
        - make install
        - cd ../..
        - pip3 install setuptools wheel
      script:
        # Rust coverage
        - cargo build --tests --all-features
        - cargo test --features kcov cli -- --test-threads 1
        - |
          for file in target/debug/{dqcsim-*,core-*}; do
            [ -x "${file}" ] || continue; 
            mkdir -p "target/cov/$(basename $file)"; 
            kcov --exclude-pattern=/.cargo,/usr/lib,/tests/ --exclude-region='#[cfg(test)]' --verify "target/cov/$(basename $file)" "$file";
          done
        # Python coverage
        - python3 setup.py build
        - kcov --python-parser=python3 --include-pattern=/python/dqcsim/ --exclude-line=no_kcoverage target/cov setup.py test
        # C++ coverage
        - python3 setup.py install
        - |
          mkdir build &&
          cd build &&
          cmake ../cpp/ &&
          make &&
          cd ../ &&
          for file in `build/test_* -executable -and -type f`; 
            do [ -x "${file}" ] || continue; 
            mkdir -p "target/cov/$(basename $file)";
            kcov --exclude-pattern=/.cargo,/usr/lib,/cpp/test_,/build/ --exclude-region='#[cfg(test)]' --verify "target/cov/$(basename $file)" "$file";
          done
        # Upload to codecov.io
        - bash <(curl -s https://codecov.io/bash)
    - name: "Manylinux wheels"
      language: generic
      os: linux
      script:
        - ./python/tools/manylinux_wheels.sh
