language: rust
sudo: false
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - python3
    - python3-dev
    - python3-setuptools
    - swig
  homebrew:
    packages:
    - python3
    - swig

env:
  global:
    - DQCSIM_HOME=$HOME/.dqcsim

install:
  - rustup component add clippy --toolchain="$TRAVIS_RUST_VERSION" || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - (test -x $HOME/.cargo/bin/cargo-make || cargo install cargo-make --vers ^0.16)
  - cargo install-update -a

script:
  - cargo fmt -- --check
  - make build
  - make test
  - cargo clippy -- -Dwarnings

before_deploy:
  - cargo doc
  - cd book && mdbook build && mdbook test
  - cp -R $TRAVIS_BUILD_DIR/target/doc/ $TRAVIS_BUILD_DIR/book/book/doc_

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book/book
  keep-history: false
  on:
    branch: master
    rust: stable
    condition: $TRAVIS_OS_NAME = linux
