language: rust
sudo: false
#dist: xenial

os:
  - linux
  - osx

rust:
  - stable
#   - nightly

# matrix:
#   fast_finish: true
#   allow_failures:
#     - rust: nightly

cache:
  directories:
    - $HOME/.cargo
    - $HOME/kcov

before_cache:
  - rm -rf $HOME/.cargo/registry

addons:
  apt:
    packages:
    # dqcsim
    - python3
    - python3-dev
    - python3-setuptools
    # python3-pip
    - swig
    # kcov
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
  homebrew:
    packages:
    # dqcsim
    - python3
    - swig

env:
  global:
    - DQCSIM_HOME=$HOME/.dqcsim
    - PATH=$PATH:$HOME/kcov/bin/

install:
  # pip3 install --upgrade pip setuptools
  - rustup component add clippy --toolchain="$TRAVIS_RUST_VERSION" || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt
  - cargo make --version || cargo install --debug cargo-make --vers "0.17.1"
  - mdbook --version || cargo install --debug mdbook --vers "0.2.3"
  - |
    (
      [ "$TRAVIS_OS_NAME" = "linux" ] &&
      [ "$TRAVIS_RUST_VERSION" = "stable" ] &&
      ( kcov --version ||
        (
          wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
          tar xzf master.tar.gz &&
          cd kcov-master &&
          mkdir build &&
          cd build &&
          cmake -DCMAKE_INSTALL_PREFIX=$HOME/kcov .. &&
          make &&
          make install 
        )
      )
    ) || echo "Skipping kcov install"

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets -- -Dwarnings
  - make kcov-test

after_success: |
  [ "$TRAVIS_OS_NAME" = "linux" ] &&
  [ "$TRAVIS_RUST_VERSION" = "stable" ] &&
  for file in target/debug/*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib,/cpp/test_,/cpp/build/,/dqcsim/tests/,/dqcsim-cli/tests,/enum-variants/tests --exclude-region='#[cfg(test)]:#[cfg(testkcovstopmarker)]' --verify "target/cov/$(basename $file)" "$file"; done &&
  for file in `find dqcsim-api/cpp/build/test_* -executable -and -type f`; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib,/cpp/test_,/cpp/build/,/dqcsim/tests/ --exclude-region='#[cfg(test)]:#[cfg(testkcovstopmarker)]' --verify "target/cov/$(basename $file)" "$file"; done &&
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/target/debug &&
  cd dqcsim-api/py &&
  kcov --python-parser=python3 --include-pattern=/py/dqcsim/ ../../target/cov setup.py test &&
  cd ../.. &&
  bash <(curl -s https://codecov.io/bash)

before_deploy:
  - cargo doc
  - cd book && mdbook build && mdbook test
  - cp -R $TRAVIS_BUILD_DIR/target/doc/ $TRAVIS_BUILD_DIR/book/book/doc_

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book/book
  keep-history: false
  on:
    branch: master
    rust: stable
    condition: $TRAVIS_OS_NAME = linux
