language: rust
sudo: false
cache: cargo

rust:
  - stable
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

install:
  - rustup component add clippy
  - rustup component add rustfmt
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test
  - cargo clippy

before_deploy:
  - cargo doc
  - cd book && mdbook build && mdbook test
  - cp -R $TRAVIS_BUILD_DIR/target/doc/ $TRAVIS_BUILD_DIR/book/book/doc_

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book/book
  keep-history: false
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
