jobs:

  - job: Python
    strategy:
      matrix:
        linux_py35:
          os: "Linux"
          image: "ubuntu-latest"
          python: "3.5"
        linux_py36:
          os: "Linux"
          image: "ubuntu-latest"
          python: "3.6"
        linux_py37:
          os: "Linux"
          image: "ubuntu-latest"
          python: "3.7"
        macos_py35:
          os: "macOS"
          image: "macos-latest"
          python: "3.5"
        macos_py36:
          os: "macOS"
          image: "macos-latest"
          python: "3.6"
        macos_py37:
          os: "macOS"
          image: "macos-latest"
          python: "3.7"
    pool:
      vmImage: $(image)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python)
        displayName: Use Python $(python)
      - script: |
          python --version
        displayName: Python version
    displayName: format('{0} Python {1}', $(os), $(python))

  - job: Rust
    strategy:
      matrix:
        linux_stable:
          os: "Linux"
          image: "ubuntu-latest"
          rust: "stable"
        macos_stable:
          os: "macOS"
          image: "macos-latest"
          rust: "stable"
    pool:
      vmImage: $(image)
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(rust)
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Use Rust $(rust)
      - script: |
          rustc --version
        displayName: Rust version
    displayName: format('{0} Rust {1}', $(os), $(rust))
