jobs:

- job:
  strategy:
    matrix:
      rust_stable_linux:
        rust: stable
        image: ubuntu-latest
      rust_stable_macos:
        rust: stable
        image: macos-latest
  pool:
    vmImage: $(image)
  steps:
  - template: templates/ci/install-rust.yml
    parameters:
      rust: $(rust)
      components: True
  - template: templates/ci/install-dependencies.yml
  - template: templates/ci/rust.yml

- job:
  strategy:
    matrix:
      python_35_linux:
        python: '3.5'
        image: ubuntu-latest
      python_36_linux:
        python: '3.6'
        image: ubuntu-latest
      python_37_linux:
        python: '3.7'
        image: ubuntu-latest
      python_35_macos:
        python: '3.5'
        image: macos-latest
      python_36_macos:
        python: '3.6'
        image: macos-latest
      python_37_macos:
        python: '3.7'
        image: macos-latest
  pool:
    vmImage: $(image)
  steps:
  - template: templates/ci/install-rust.yml
  - template: templates/ci/install-python.yml
    parameters:
      python: $(python)
  - template: templates/ci/install-dependencies.yml
  - template: templates/ci/python.yml

- job:
  strategy:
    matrix:
      cpp_linux:
        image: ubuntu-latest
      cpp_macos:
        image: macos-latest
  pool:
    vmImage: $(image)
  steps:
  - template: templates/ci/install-rust.yml
  - template: templates/ci/cpp.yml
