jobs:

  - job: Python
    strategy:
      matrix:
        linux_py35:
          image: "ubuntu-latest"
          python: "3.5"
        linux_py36:
          image: "ubuntu-latest"
          python: "3.6"
        linux_py36:
          image: "ubuntu-latest"
          python: "3.7"
        macos_py35:
          image: "macos-latest"
          python: "3.5"
        macos_py36:
          image: "macos-latest"
          python: "3.6"
        macos_py37:
          image: "macos-latest"
          python: "3.7"
    pool:
      vmImage: $(image)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python)
        displayName: Use Python $(python)
      - script: |
          python --version
        displayName: Python version

  - job: Rust
    strategy:
      matrix:
        linux_stable:
          image: "ubuntu-latest"
          rust: "stable"
        macos_stable:
          image: "macos-latest"
          rust: "stable"
    pool:
      vmImage: $(image)
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(rust)
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Use Rust $(rust)
      - script: |
          rustc --version
        displayName: Rust version
