[workspace]

members = [
  "dqcsim",
  "dqcsim-cli",
  "dqcsim-api",
  "lib/enum-variants",
  "lib/enum-variants-derive",
  "plugins/dqcsfenull",
  "plugins/dqcsopnull",
  "plugins/dqcsbenull",
]

[profile.release]
rpath = true
