[package]
name = "dqcsim-rs"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.0"
structopt = "0.2"

riker = "0.2"
riker-default = "0.2"
riker-patterns = "0.2"
futures-preview = "0.3.0-alpha.12"
