[workspace]

members = [
  "dqcsim",
  "dqcsim-cli",
  "dqcsim-plugin",
  # Not part of the workspace yet as it requires rust nightly:
  # https://github.com/PyO3/pyo3/issues/5
  # https://github.com/PyO3/pyo3/issues/210
  # "dqcsim-py",
]
