coverage:
  status:
    project:
      default:
        threshold: 1
      rust:
        paths: rust/
      # cpp:
      #   paths:
      #     - cpp/
      #     - target/include/
      python:
        paths: python/
