[tasks.format]
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt"]

[tasks.clippy]
install_crate = { rustup_component_name = "clippy", binary = "clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]

[tasks.doc]
command = "cargo"
args = ["doc"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.commit]
dependencies = [
    "format",
    "clippy",
    "build",
    "doc",
    "test"
]

[tasks.install]
dependencies = [
    "release",
]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
