[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]

[tasks.fix]
install_crate = "fix"
command = "cargo"
args = ["fix", "--allow-dirty", "--allow-staged"]

[tasks.doc]
command = "cargo"
args = ["doc"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.commit]
dependencies = [
    "format",
    "fix",
    "clippy",
    "build",
    "doc",
    "test"
]

[tasks.install]
dependencies = [
    "release",
]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"
