[package]
name = "dqcsim"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
dqcsim-core = { path = "../dqcsim-core" }

slog = "2.4"
slog-term = "2.4"
slog-async = "2.3"
slog-scope = "4.1"
slog-stdlog = "3.0"

log = "0.4"
structopt = "0.2"
clap = "2.32"
