[package]
name = "dqcsim-log"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.3"
humantime = "1.2"
term = "0.5"
