[package]
name = "dqcsim-log"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["serde"] }

crossbeam-channel = "0.3"

# Serialization and deserialization
serde = { version = "1.0", features = ["derive"] }
