[package]
name = "dqcsim-core"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"

serde = { version = "1.0", features = ["derive"] }
ipc-channel = { version = "0.11", features = ["async"] }
