[package]
name = "dqcsim-plugin"
version = "0.1.0"
authors = ["Matthijs Brobbel", "Jeroen van Straten"]
edition = "2018"

[dependencies]
dqcsim = { path = "../dqcsim" }

structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
ipc-channel = { version = "0.11" }
failure = "0.1"
