// <cdqcsim> -*- C++ -*-

#ifndef _CDQCSIM_INCLUDED_
//! \cond Doxygen_Suppress
#define _CDQCSIM_INCLUDED_
//! \endcond

/*!
 * \file cdqcsim
 * \brief Provides DQCsim's raw C API symbols in the `dqcsim::raw` namespace.
 *
 * This is file is functionally identical to `dqcsim.h`, but doesn't pollute
 * the global namespace.
 */

#include <cstdio>
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <new>

//! \cond Doxygen_Suppress
#ifndef _DQCSIM_HDR_CPP_
#define _DQCSIM_HDR_CPP_
#endif
//! \endcond

#ifdef __cplusplus
extern "C" {
#endif
