[tasks.build]
clear = true
command = "make"
args = ["all"]

[tasks.clean]
clear = true
command = "make"
args = ["clean"]

[tasks.install]
dependencies = ["release"]
command = "make"
args = ["install"]
