[package]
name = "dqcsim-py"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[lib]
name = "dqcsim_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.6.0-alpha.4", features = ["extension-module"] }
