name: Coverage

on:
  push:
    paths:
    - 'rust/**'
    - '**/Cargo.toml'
    - '**/Cargo.lock'
    - 'cpp/**'
    - '**/CMakeLists.txt'
    - 'python/**'
    - '**/setup.py'
  pull_request:

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C link-dead-code
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --no-default-features --features null-plugins --bins --manifest-path rust/Cargo.toml
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-run --all-features --all-targets
    - uses: docker://kcov/kcov:v37
      with:
        entrypoint: true
    - name: Kcov
      run: |
        docker run --rm --security-opt seccomp=unconfined \
          --workdir /home/runner/work/dqcsim/dqcsim \
          -e INPUT_ENTRYPOINT \
          -e INPUT_ARGS \
          -e HOME \
          -e GITHUB_REF \
          -e GITHUB_SHA \
          -e GITHUB_REPOSITORY \
          -e GITHUB_ACTOR \
          -e GITHUB_WORKFLOW \
          -e GITHUB_HEAD_REF \
          -e GITHUB_BASE_REF \
          -e GITHUB_EVENT_NAME \
          -e GITHUB_WORKSPACE \
          -e GITHUB_ACTION \
          -e GITHUB_EVENT_PATH \
          -e RUNNER_OS \
          -e RUNNER_TOOL_CACHE \
          -e RUNNER_TEMP \
          -e RUNNER_WORKSPACE \
          -e ACTIONS_RUNTIME_URL \
          -e ACTIONS_RUNTIME_TOKEN \
          -e GITHUB_ACTIONS=true \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "/home/runner/work/dqcsim/dqcsim":"/home/runner/work/dqcsim/dqcsim" \
          --entrypoint "/bin/bash" \
          kcov/kcov:v37 \
          -c "mkdir -p target/cov/rust && find target/debug/{dqcsim-*,core-*} -type f -executable | xargs -l kcov --include-path=rust/ --exclude-region='#[cfg(test)]' target/cov/rust"
    - name: Filter output
      run: |
        mkdir -p rust-cov
        find target/cov/rust -type f -name "cobertura.xml" -o -name "coverage.json" | xargs tar -cf rust-cov/rust-cov.tar
    - uses: actions/upload-artifact@v1
      with:
        name: rust-cov
        path: rust-cov

  cpp:
    name: C++
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C link-dead-code
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Install CMake
      run: |
        mkdir -p $HOME/cmake
        curl -L https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.tar.gz | tar xz --strip-components=1 -C $HOME/cmake
        echo "::add-path::${HOME}/cmake/bin"
    - name: Build
      run: |
        cmake . -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
        make -j
    - uses: docker://kcov/kcov:v37
      with:
        entrypoint: true
    - name: Kcov
      run: |
        docker run --rm --security-opt seccomp=unconfined \
          --workdir /home/runner/work/dqcsim/dqcsim \
          -e INPUT_ENTRYPOINT \
          -e INPUT_ARGS \
          -e HOME \
          -e GITHUB_REF \
          -e GITHUB_SHA \
          -e GITHUB_REPOSITORY \
          -e GITHUB_ACTOR \
          -e GITHUB_WORKFLOW \
          -e GITHUB_HEAD_REF \
          -e GITHUB_BASE_REF \
          -e GITHUB_EVENT_NAME \
          -e GITHUB_WORKSPACE \
          -e GITHUB_ACTION \
          -e GITHUB_EVENT_PATH \
          -e RUNNER_OS \
          -e RUNNER_TOOL_CACHE \
          -e RUNNER_TEMP \
          -e RUNNER_WORKSPACE \
          -e ACTIONS_RUNTIME_URL \
          -e ACTIONS_RUNTIME_TOKEN \
          -e GITHUB_ACTIONS=true \
          -e LD_LIBRARY_PATH=/home/runner/work/dqcsim/dqcsim/target/debug \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "/home/runner/work/dqcsim/dqcsim":"/home/runner/work/dqcsim/dqcsim" \
          --entrypoint "/bin/bash" \
          kcov/kcov:v37 \
          -c "mkdir -p target/cov/cpp && find dqcsim_tests_* -executable -and -type f | xargs -l kcov --include-path=cpp/,rust/ --exclude-path=cpp/test/ target/cov/cpp"
    - name: Filter output
      run: |
        mkdir -p cpp-cov
        find target/cov/cpp -type f -name "cobertura.xml" -o -name "coverage.json" | xargs tar -cf cpp-cov/cpp-cov.tar
    - uses: actions/upload-artifact@v1
      with:
        name: cpp-cov
        path: cpp-cov

  python:
    name: Python
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C link-dead-code
      DQCSIM_DEBUG: ''
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - uses: actions/setup-python@v1
    - name: Install Swig
      run: |
        sudo apt-get install -y swig
    - name: Install dependencies
      run: |
        python3 -m pip install wheel
    - name: Build
      run: |
        python setup.py build
    - uses: docker://kcov/kcov:v37
      with:
        entrypoint: true
    - name: Kcov
      run: |
        docker run --rm --security-opt seccomp=unconfined \
          --workdir /home/runner/work/dqcsim/dqcsim \
          -e DQCSIM_DEBUG \
          -e INPUT_ENTRYPOINT \
          -e INPUT_ARGS \
          -e HOME \
          -e GITHUB_REF \
          -e GITHUB_SHA \
          -e GITHUB_REPOSITORY \
          -e GITHUB_ACTOR \
          -e GITHUB_WORKFLOW \
          -e GITHUB_HEAD_REF \
          -e GITHUB_BASE_REF \
          -e GITHUB_EVENT_NAME \
          -e GITHUB_WORKSPACE \
          -e GITHUB_ACTION \
          -e GITHUB_EVENT_PATH \
          -e RUNNER_OS \
          -e RUNNER_TOOL_CACHE \
          -e RUNNER_TEMP \
          -e RUNNER_WORKSPACE \
          -e ACTIONS_RUNTIME_URL \
          -e ACTIONS_RUNTIME_TOKEN \
          -e GITHUB_ACTIONS=true \
          -v "/var/run/docker.sock":"/var/run/docker.sock" \
          -v "/home/runner/work/_temp/_github_home":"/github/home" \
          -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
          -v "/home/runner/work/dqcsim/dqcsim":"/home/runner/work/dqcsim/dqcsim" \
          --entrypoint "/bin/bash" \
          kcov/kcov:v37 \
          -c "apt-get update && apt-get install -y python3 python3-pip && python3 -m pip install setuptools wheel && mkdir -p target/cov/python && kcov --include-path=python/dqcsim/,rust/ --exclude-line='no_kcoverage,#@,assert(False)' --exclude-pattern=/tests --python-parser=python3 target/cov/python setup.py test"
    - name: Filter output
      run: |
        mkdir -p python-cov
        find target/cov/python -type f -name "cobertura.xml" -o -name "coverage.json" | xargs tar -cf python-cov/python-cov.tar
    - uses: actions/upload-artifact@v1
      with:
        name: python-cov
        path: python-cov

  upload:
    name: Codecov.io
    runs-on: ubuntu-latest
    needs: [rust, cpp, python]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: rust-cov
    - uses: actions/download-artifact@v1
      with:
        name: cpp-cov
    - uses: actions/download-artifact@v1
      with:
        name: python-cov
    - name: Extract
      run: |
        find . -name "*-cov.tar" | xargs -l tar -xf
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
