name: Documentation

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        brew install swig doxygen
        python -m pip install pdoc3 setuptools wheel
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - name: Install mdbook
      run: |
        mkdir -p $HOME/mdbook
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.0/mdbook-v0.4.0-x86_64-apple-darwin.tar.gz | tar xz -C $HOME/mdbook
        echo "${HOME}/mdbook/" >> $GITHUB_PATH
    - name: Install dqcsim
      env:
        DQCSIM_DEBUG: ''
      run: |
        python setup.py bdist_wheel
        python -m pip install target/python/dist/*.whl
    - name: Build
      working-directory: ./doc
      run: |
        make all
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: target/book

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: book
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
