#include <dqcsim_raw.hpp>
#include "gtest/gtest.h"

using namespace dqcsim;

// Test the error get/set API.
TEST(error, test) {
  // There should initially not be any errors.
  EXPECT_STREQ(dqcs_error_get(), NULL);

  // Getting the errors generated by the API calls is already tested ad nauseum
  // in all the other test files, so we set our own error here, which has not
  // been tested yet.
  dqcs_error_set("Hi, I'm an error");
  EXPECT_STREQ(dqcs_error_get(), "Hi, I'm an error");

  // Make sure that dqcs_error_set() makes a copy.
  char buf[14] = "Hello, world!";
  dqcs_error_set(buf);
  EXPECT_STREQ(dqcs_error_get(), "Hello, world!");
  strcpy(buf, "Hello, C API!");
  EXPECT_STREQ(dqcs_error_get(), "Hello, world!");

  // Check that clearing the error string works.
  dqcs_error_set(NULL);
  EXPECT_STREQ(dqcs_error_get(), NULL);

  // Leak check.
  EXPECT_EQ(dqcs_handle_leak_check(), dqcs_return_t::DQCS_SUCCESS) << dqcs_error_get();
}
